gnu++20:fix build error.
make[2]: *** [/home/cuiziwei/vela/vela-all/apps/Application.mk:207: src/cpp-lib/core/EventManager.cpp.home.cuiziwei.vela.vela-all.vendor.xiaomi.miai.mibrainsdk.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/thread:96,
                 from src/cpp-lib/ws/WsClient.h:12,
                 from src/cpp-lib/core/EngineImpl.h:10,
                 from src/cpp-lib/core/Worker.cpp:9:
/home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__thread/thread.h: In instantiation of 'void std::__1::__thread_execute(tuple<_TSp, _Fp, _Args ...>&, __tuple_indices<_Np ...>) [with _TSp = unique_ptr<__thread_struct>; _Fp = thread::attributes; _Args = {void (*)(void*), aivs::Worker*}; unsigned int ..._Indices = {2, 3}]':
/home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__thread/thread.h:259:28:   required from 'void* std::__1::__thread_proxy(void*) [with _Fp = tuple<unique_ptr<__thread_struct, default_delete<__thread_struct> >, thread::attributes, void (*)(void*), aivs::Worker*>]'
/home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__thread/thread.h:275:45:   required from 'std::__1::thread::thread(_Fp&&, _Args&& ...) [with _Fp = attributes&; _Args = {void (&)(void*), aivs::Worker*}; <template-parameter-1-3> = void]'
src/cpp-lib/core/Worker.cpp:31:48:   required from here
/home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__thread/thread.h:248:20: error: use of deleted function 'std::__1::__nat::~__nat()'
  248 |     _VSTD::__invoke(_VSTD::move(_VSTD::get<1>(__t)), _VSTD::move(_VSTD::get<_Indices>(__t))...);
      |                    ^
In file included from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__type_traits/is_swappable.h:23,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__utility/swap.h:17,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__concepts/swappable.h:24,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__concepts/movable.h:14,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__concepts/copyable.h:14,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__iterator/iterator_traits.h:16,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__algorithm/unwrap_iter.h:13,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__algorithm/equal.h:14,
                 from /home/cuiziwei/vela/vela-all/nuttx/include/libcxx/map:574,
                 from src/cpp-lib/core/EngineImpl.h:9:
/home/cuiziwei/vela/vela-all/nuttx/include/libcxx/__type_traits/nat.h:25:3: note: declared here
   25 |   ~__nat()                       = delete;
      |   ^

Signed-off-by: cuiziwei <cuiziwei@xiaomi.com>